version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t lib # save requirements into lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .    # zip requirements for deployment
      - cd ..
      - zip -g deployment_package.zip app.py   # add app to deployment zip
  post_build:
    commands:
      - echo "Updating lambda function..."
      - aws lambda update-function-code --function-name hci-project-1 --zip-file fileb://deployment_package.zip
      - echo "Done."